language: node_js
node_js:
    - "14"
cache:
    npm: false
    directories:
        - "~/.pnpm-store"

jobs:
    include:
        - stage: build
          before_install:
            - curl -L https://unpkg.com/@pnpm/self-installer | node
            - pnpm config set store-dir ~/.pnpm-store
            - pnpm install
        - script: npm run prettier-ci
          name: "Prettier"
        - script: npm run test
          name: "Tests"
        - script: npm run build
          name: "Build"
