// Generated by https://coolors.co/c6d8ff-71a9f7-6b5ca5-72195a-4c1036
const palette = {
	primary: {
		light: "#4C536B",
		main: "#2B2F3D",
		dark: "#111218",
	},
	secondary: {
		light: "#DDE1E4",
		main: "#b0bac2",
		dark: "#A4AFB6",
	},
	tertiary: {
		light: "#FFE75C",
		main: "#FFD700",
		dark: "#E0BF00",
	},
	error: "#b20300",
	success: "#00b206",
	info: "#00b8ff",
}

export default palette
