// Generated by https://coolors.co/c6d8ff-71a9f7-6b5ca5-72195a-4c1036
const palette = {
    primary: {
        main: '#2B2F3D'
    },
    secondary: {
        main: '#b0bac2'
    },
    tertiary: {
        main: '#fff100'
    },
    error: '#b20300',
    success: '#00b206',
    info: '#00b8ff'
};

export default palette;
