export const HOME_ROUTE = "/"
export const LOGIN_ROUTE = "/login"
export const CHANGE_PASSWORD_ROUTE = "/setup"
export const API_OFFLINE_ERROR = "/offline"
export const PLAYERS_ROUTE = "/players"
export const COMPETITIONS_ROUTE = "/competitions"
